### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by carlskii** [kikocorreoso/brythonmagic#11]
I'm a little confused, whilst brython looks to be an excellent way of bridging the JS/Python space, I thought that iPython Notebooks natively  ? So I'm just curious as to whether this integration with HighCharts can be achieve without brython ?

I would love to get this stuff clarified as I've already wasted loads of time  trying to get HC working using the native JS support - without much success.

**Comment by kikocorreoso** [comment]
Brython is a python implementation written in javascript so in the end you are using javascript with a pythonic syntax.

Highcharts runs in the client side and python (CPython) can't run in the client (the browser). This is why you need Brython if you want to run HC using Python syntax (on the client side).

IPython notebook architecture is, summarised:

* A kernel running in the backend/server side. The kernel can be CPython but it also can be Julia, R, Haskell,... This is why now IPython is called Jupyter (kernel agnostic infrastructure).
* The frontend/client-side where you run technology understood by the browser (HTML/css/javascript).
* A messaging system to connect the client and the server.

If you run something that is pure javascript, like HC, you need to create a wrapper to communicate with the kernel and pass information between the client (javascript) and the kernel (that can be CPython or others). If you just want to run the visualisation on the client side you can use Brython as it is already javascript and can access javascript directly without the need to create a wrapper for it.

I don't know if this helps you clarify your doubts.

**Comment by carlskii** [comment]
Thanks - that makes perfect sense now !
