### ISSUE TITLE
broken package?

### ISSUE THREAD

**Issue by AndrewAnnex** [kikocorreoso/brythonmagic#12]
I was trying out the open layers example on a recent version of jupyter and python 3.7 and I only see the script outputs in the cells not the interactive maps.

**Comment by kikocorreoso** [comment]
Hi.

The package is not updated since a while ago and I would need some time to check latest jupyter and brython versions.. Also, IIRC, the examples are using openlayers2. Last openlayers version is 5.3.0...

Maybe you can try a newer openlayers version and let me now if it is working. If it is not working just send a new comment using this thread and detailing the errors. If it is working you can send a PR with your new examples :-)

**Comment by jkrys** [comment]
Hi.
I managed to load brython library into my Jupyter Notebook but I have an error in running even the simplest example as:

%%brython -p -c my_div
print("Hello")
document[my_div]<=html.P("Hi")

and it outputs with:

<script id="564445" type="text/python">
print("Hello")
document[my_div]<=html.P("Hi")
  </script>
  <div id="my_div"></div>
  <script type="text/javascript">brython({debug:1, static_stdlib_import: false, ipy_id: ["564445"]});</script>

The error in the console is:

[Log] ReferenceError: Can't find variable: $locals___main__ (brython.min.js, line 7)
[Log] Javascript error – ReferenceError: Can't find variable: $locals___main__ (brython.min.js, line 7)
ReferenceError: Can't find variable: $locals___main__
[Error] Traceback (most recent call last):
undefined: ReferenceError: Can't find variable: $locals___main__
	(anonymous function) (brython.min.js:7:202122)
	$ (brython.min.js:7:172561)
	(anonymous function) (brython.min.js:7:162241)
	(anonymous function) (brython.min.js:7:160139)
	Global Code (Script Element 13:1)
	appendChild
	DOMEval (main.min.js:124)
	domManip (main.min.js:5945)
	append (main.min.js:6081)
	(anonymous function) (main.min.js:45466)
	(anonymous function) (main.min.js:45669)
	(anonymous function) (main.min.js:45355)
	(anonymous function) (main.min.js:45266)
	output (main.min.js:47115)
	(anonymous function) (main.min.js:48875)
	proxy (main.min.js:10502)
	promiseReactionJob
[Error] Error
	(anonymous function) (brython.min.js:7:162286)
	(anonymous function) (brython.min.js:7:160139)
	Global Code (Script Element 13:1)
	appendChild
	DOMEval (main.min.js:124)
	domManip (main.min.js:5945)
	append (main.min.js:6081)
	(anonymous function) (main.min.js:45466)
	(anonymous function) (main.min.js:45669)
	(anonymous function) (main.min.js:45355)
	(anonymous function) (main.min.js:45266)
	output (main.min.js:47115)
	(anonymous function) (main.min.js:48875)
	proxy (main.min.js:10502)
	promiseReactionJob


I know you haven't updated the package for a while but maybe you have some ideas how can I fix this issue?

**Comment by kikocorreoso** [comment]
Hi,

I've updated the package. You can try the development version. I've updated the [README](https://github.com/kikocorreoso/brythonmagic/blob/master/README.md) with instructions to install the development version.

There are [some](https://github.com/kikocorreoso/brythonmagic/issues/16) [issues](https://github.com/kikocorreoso/brythonmagic/issues/17) that need to be solved before uploading a new version to PyPI. In the meantime you could use the version from master.

**Comment by jkrys** [comment]
It's working now! Thank you!
