### ISSUE TITLE
Does print() work ?

### ISSUE THREAD

**Issue by stuaxo** [kikocorreoso/brythonmagic#14]
I was expecting to be able to do something like

```%%brythonmagic
print(1)
```

And see the output in the cell, are my expectations incorrect (I guess maybe I'm after a brython kernel ?)

**Comment by kikocorreoso** [comment]
Hi @stuaxo 

`print` is shown in the js console.

From the [brython docs here](https://brython.info/static_doc/en/syntax.html): 

`by default, print() will output to the web browser console and so are the error messages. sys.stderr and sys.stdout can be assigned to an object with a write() method, and this allows for the redirection of output to go to a window or text area, for example. `

If you want to print something in the notebook just use the regular python (a `print` without the `brython` cell magics in the cell) :wink:

**Comment by stuaxo** [comment]
Cheers.
